In [1]:
import torch
torch.__version__

'2.4.0+cu118'

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#Matrix
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
#Tensor
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

In [14]:
random_tensor = torch.rand(3,4)
random_tensor_2 = torch.rand(size=(5,5))
random_tensor, random_tensor.dtype
random_tensor_2, random_tensor_2.dtype

(tensor([[0.9322, 0.5284, 0.5901, 0.9269, 0.9423],
         [0.0832, 0.3443, 0.3452, 0.1864, 0.5054],
         [0.2221, 0.9842, 0.9345, 0.4447, 0.6086],
         [0.1876, 0.8469, 0.6376, 0.3802, 0.4683],
         [0.2608, 0.3625, 0.9837, 0.4090, 0.2003]]),
 torch.float32)

In [15]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [16]:
zeros = torch.zeros(size=(6,6))
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [17]:
ones = torch.ones(size=(6,6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [18]:
range_ = torch.arange(start=0, end=10, step=1)
range_

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
ten_zeros = torch.zeros_like(input=range_)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
ten_ones = torch.ones_like(input=range_)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, # type of tensor
                              device=None, # cpu or gpu. None's means cpu
                              requires_grad=False) # This flag indicates whether or not PyTorch should track operations on the tensor for automatic differentiation (used in backpropagation).
float_32_tensor, float_32_tensor.shape, float_32_tensor.ndim, float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.Size([3]), 1, torch.float32, device(type='cpu'))

In [22]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work
float_16_tensor.dtype

torch.float16

In [24]:
# Create a tensor
some_tensor = torch.rand(3, 4)
# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.8613, 0.3868, 0.5746, 0.7132],
        [0.0375, 0.2373, 0.5117, 0.9846],
        [0.9693, 0.7072, 0.4167, 0.0829]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [25]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [26]:
tensor * 10

tensor([10, 20, 30])

In [27]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [28]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [29]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [30]:
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [31]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [32]:
tensor * tensor

tensor([1, 4, 9])

In [33]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [34]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

In [35]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [36]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [37]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [40]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)
x=tensor_A
output = linear(x)
print(f"input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [42]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
print(f"Minimum Number: {x.min()}")
print(f"Maximum Number: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")
#  torch.mean() require tensors to be in torch.float32 (the most common)

Minimum Number: 0
Maximum Number: 90
Mean: 45.0
Sum: 450


In [45]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [46]:
tensor = torch.arange(10,100,10)
print(f"Tensor: {tensor}")
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [47]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [48]:
tensor_float_16 = tensor.type(torch.float16)
tensor_float_16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [49]:
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [50]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [51]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [52]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [56]:
x_stacked = torch.stack([x, x, x, x], dim=-2) # try changing dim to dim=1 and see what happens [-2,1]
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [57]:
import torch
x = torch.tensor([[[1, 2, 3]]])  # shape: (1, 1, 3)
print(x.shape)  # Output: torch.Size([1, 1, 3])
# Using squeeze to remove all size 1 dimensions
x_squeezed = x.squeeze()
print(x_squeezed.shape)  # Output: torch.Size([3])

torch.Size([1, 1, 3])
torch.Size([3])


In [58]:
x = torch.tensor([[[1, 2, 3]]])  # shape: (1, 1, 3)
print(x.shape)  # Output: torch.Size([1, 1, 3])
# Remove only the second dimension (dim=1)
x_squeezed = x.squeeze(dim=1)
print(x_squeezed.shape)  # Output: torch.Size([1, 3])

torch.Size([1, 1, 3])
torch.Size([1, 3])


In [59]:
x = torch.tensor([[1, 2, 3]])  # shape: (1, 3)
# Attempt to squeeze the second dimension (dim=1)
x_squeezed = x.squeeze(dim=1)
print(x_squeezed.shape)  # Output: torch.Size([1, 3])

torch.Size([1, 3])


In [60]:
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)
print(f"Previous shape: {x_original}")
print(f"New Shape: {x_permuted.shape}")

Previous shape: tensor([[[0.2666, 0.6274, 0.2696],
         [0.4414, 0.2969, 0.8317],
         [0.1053, 0.2695, 0.3588],
         ...,
         [0.5697, 0.2088, 0.6539],
         [0.3397, 0.9565, 0.0660],
         [0.3421, 0.0172, 0.3031]],

        [[0.6576, 0.9813, 0.5840],
         [0.9902, 0.5978, 0.7888],
         [0.9008, 0.9180, 0.2201],
         ...,
         [0.5322, 0.8510, 0.4556],
         [0.1844, 0.8533, 0.5698],
         [0.3568, 0.1704, 0.6172]],

        [[0.0231, 0.6317, 0.7472],
         [0.0614, 0.1727, 0.1405],
         [0.9203, 0.9251, 0.5313],
         ...,
         [0.4989, 0.0933, 0.3064],
         [0.6272, 0.5955, 0.8636],
         [0.8345, 0.2273, 0.2865]],

        ...,

        [[0.3599, 0.1989, 0.5711],
         [0.5387, 0.1378, 0.9763],
         [0.5521, 0.6004, 0.1658],
         ...,
         [0.1790, 0.9954, 0.6617],
         [0.9871, 0.5877, 0.7375],
         [0.1551, 0.7881, 0.3759]],

        [[0.7442, 0.8621, 0.7548],
         [0.6381, 0.0106, 0.089

In [61]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [62]:
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [63]:
import torch
torch.cuda.is_available()

True

In [64]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [65]:
# Count number of devices
torch.cuda.device_count()

1